function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
function order(name, price) {
  const col = +prompt(`Сколько ${name} хотите заказать?`, "");
  const totalPrice = col * price;
  confirm(`За ${col} ${name} вы заказываете на ${totalPrice} so'm`);
}
